name: Build and deploy Node.js app to Azure Web App - designquest-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2481331CDC2E495BA743BC6F74594E03 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC540949E54D468A83FA432CC25B00C0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D60B3AB7706C4FAD8D8205F957C6C920 }}

      - name: Configure App Service (build + startup)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name designquest-app \
              --resource-group designquest-app_group \
              --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true

            az webapp config set \
              --name designquest-app \
              --resource-group designquest-app_group \
              --startup-file "npm start"

      - name: Deploy source to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'designquest-app'
          slot-name: 'Production'
          package: .
          